trigger:
- main

pool:
  name: dhurander

stages:
  - stage:
    displayName: build
    jobs:
      - job: 
        displayName: image build
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker-rg'
            repository: 'ankitlodhi11/axion-system'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'axionaks'
            command: 'create'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'